### ISSUE TITLE
field definiton: Is Searchable => default options

### ISSUE THREAD

**Issue by fiorenzino** [snello-cms/snello-admin#14]
When you choose "Is Searchable" => default option on "Search Condition" should be "contains"

**Comment by Rubliev** [comment]
Default values:   
   input: contains
    select: exact
    date: exact
    datetime: exact
    time: exact
    checkbox: exact
    textarea: contains
    tinymce: contains
    ace9: contains
    tags: contains (??)
    join: exact
    multijoin: contains(??)
    media: non searchable

**Comment by Rubliev** [comment]
for all contains case insensitve search is used
