### ISSUE TITLE
content list: load of metadata in multijoin relationship

### ISSUE THREAD

**Issue by fiorenzino** [snello-cms/snello-admin#23]
the list should load from rest api only the values specified in the FieldDefinition object ( we can use the selectField).
On every rest call we can use the query parameter "select_fields" to select a subset of fields 

example of rest call:

fieldDefinitionX.selectFields =name,year

http://localhost:4200/api/{table_to_fetch}/{condition_uuid}?select_fields=name,year

Realistic example:
http://localhost:4200/api/opera/operetta-breve?select_fields=name,year

**Comment by Rubliev** [comment]
ok
